[tool.poetry]
name = "klauss"
version = "0.1.0"
description = "Joc"
authors = ["Trobanoms i iwi"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
